/*nome do banco testeSQLTrab2, usuario = usuario, senha = usuario*/

CREATE TABLE AMIGO(
    id INTEGER  PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
    NOME VARCHAR (150)  NOT NULL, 
    EMAIL VARCHAR (150)  NOT NULL, 
    SENHA VARCHAR (150)  NOT NULL, 
    AMIGOSELECIONADO INTEGER   
)


CREATE TABLE EVENTO(
    CODIGO VARCHAR (150)  PRIMARY KEY NOT NULL, 
    TITULO VARCHAR (150)  NOT NULL, 
    MINIMO DOUBLE  NOT NULL, 
    DATAEVENTO DATE NOT NULL,
    sorteio DATE NOT NULL
)

CREATE TABLE AMIGOEVENTO(
    IDAMIGO INTEGER NOT NULL,
    IDEVENTO VARCHAR(150)
)

INSERT INTO amigo(nome,email,senha) values('IGOR', 'IGOR@IGOR.COM', 'IGOR');
INSERT INTO amigo(nome,email,senha) values('YAN', 'YAN@YAN.COM', 'YAN');
INSERT INTO amigo(nome,email,senha) values('PITUBA', 'PITUBA@PITUBA.COM', 'PITUBA');
INSERT INTO amigo(nome,email,senha) values('FERNANDA', 'FERNANDA@FERNANDA.COM', 'FERNANDA');
INSERT INTO amigo(nome,email,senha) values('ANDREIA', 'ANDREIA@ANDREIA.COM', 'ANDREIA');
INSERT INTO amigo(nome,email,senha) values('USUARIO', 'USUARIO@USUARIO.COM', 'USUARIO');
INSERT INTO amigo(nome,email,senha) values('ALUNO', 'ALUNO@ALUNO.COM', 'ALUNO');
INSERT INTO evento(codigo,titulo,minimo,dataevento,sorteio) values('PRIMEIRO AMIGO OCULTO', 'AMIGO OCULTO 1', 20, '2018-06-15', '2018-06-20');
INSERT INTO evento(codigo,titulo,minimo,dataevento,sorteio) values('SEGUNDO AMIGO OCULTO', 'AMIGO OCULTO 1', 20, '2018-07-20', '2018-08-20');
INSERT INTO AMIGOEVENTO(IDEVENTO,IDAMIGO) VALUES('PRIMEIRO AMIGO OCULTO', 1 );
INSERT INTO AMIGOEVENTO(IDEVENTO,IDAMIGO) VALUES('PRIMEIRO AMIGO OCULTO', 2 );
INSERT INTO AMIGOEVENTO(IDEVENTO,IDAMIGO) VALUES('PRIMEIRO AMIGO OCULTO', 3 );
INSERT INTO AMIGOEVENTO(IDEVENTO,IDAMIGO) VALUES('PRIMEIRO AMIGO OCULTO', 4 );