
CREATE TABLE AMIGO(
    id INTEGER  PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
    NOME VARCHAR (150)  NOT NULL, 
    EMAIL VARCHAR (150)  NOT NULL, 
    SENHA VARCHAR (150)  NOT NULL, 
    AMIGOSELECIONADO INTEGER   
)


CREATE TABLE EVENTO(
    CODIGO VARCHAR (150)  PRIMARY KEY NOT NULL, 
    TITULO VARCHAR (150)  NOT NULL, 
    MINIMO DOUBLE  NOT NULL, 
    'DATA' DATE NOT NULL,
    sorteio DATE NOT NULL
)

CREATE TABLE AMIGOEVENTO(
    IDAMIGO INTEGER NOT NULL,
    IDEVENTO VARCHAR(150)
)
